/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Lumberjack.gltf
Author: micaelsampaio (https://sketchfab.com/micaelsampaio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lumberjack-low-poly-character-d88d033c86a243f78349f935f78ba057
Title: Lumberjack Low Poly Character
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Lumberjack = ({ position, scale, rotation, ...props }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Lumberjack.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['Talking'].reset().fadeIn(0.5).play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={scale} position={position}>
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Cube001_Cube003"
            geometry={nodes.Cube001_Cube003.geometry}
            material={materials['Material.001']}
            skeleton={nodes.Cube001_Cube003.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Cube002_Cube004"
            geometry={nodes.Cube002_Cube004.geometry}
            material={materials['Material.001']}
            skeleton={nodes.Cube002_Cube004.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Cube_Cube001"
            geometry={nodes.Cube_Cube001.geometry}
            material={materials['Material.001']}
            skeleton={nodes.Cube_Cube001.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Cylinder001_Cylinder004"
            geometry={nodes.Cylinder001_Cylinder004.geometry}
            material={materials['Material.001']}
            skeleton={nodes.Cylinder001_Cylinder004.skeleton}
            castShadow
            receiveShadow
          />
          <skinnedMesh
            name="Cylinder_Cylinder002"
            geometry={nodes.Cylinder_Cylinder002.geometry}
            material={materials['Material.001']}
            skeleton={nodes.Cylinder_Cylinder002.skeleton}
            castShadow
            receiveShadow
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Lumberjack.glb')

export default Lumberjack
